package ui

enum class MainMenuOption {
    PLACEHOLDER,
    BACK_TO_LOGIN_PAGE,
    SCENIC_SPOT_MANAGEMENT, ROUTE_MANAGEMENT,
    QUERY_SCENIC_SPOT, VIEW_SCENIC_SPOT_MAP, QUERY_DISTANCE, QUERY_TOURIST_ROUTE,
    PARKING_LOT_EMULATOR, VIEW_NOTICE,
    EXIT
}