package ui

enum class MainMenuOption {
    BACK_TO_LOGIN_PAGE,
    SCENIC_SPOT_MANAGEMENT, ROUTE_MANAGEMENT,
    QUERY_SCENIC_SPOT, VIEW_SCENIC_SPOT_MAP, QUERY_DISTANCE, VIEW_TOURIST_ROUTE,
    PARKING_LOT_EMULATOR, NOTICE_MANAGEMENT, VIEW_NOTICE,
    EXIT
}